export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const FETCH_MUSEUM_DATA = 'FETCH_MUSEUM_DATA';
export const FETCH_EXHIBITION_DATA = 'FETCH_EXHIBITION_DATA';
export const FETCH_PROFILE_DATA = 'FETCH_PROFILE_DATA';
